LMSLexicon20/Models/Module.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LMSLexicon20.Models
{
    public class Module
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Description { get; set; }

        //Foreign Key
        public int CourseId { get; set; }

        //Navigation Prop
        public Course Course { get; set; }
        public ICollection<Activity> Activities { get; set; }
        public ICollection<Document> Documents { get; set; }

    }
}

LMSLexicon20/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMSLexicon20.Data;
using LMSLexicon20.Models;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using LMSLexicon20.Models.ViewModels;

namespace LMSLexicon20.Controllers
{
    public class ActivitiesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper mapper;

        public ActivitiesController(ApplicationDbContext context ,IMapper mapper )
        {
            _context = context;
            this.mapper = mapper;
        }

        // GET: Activities
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Index()
        {
            //var applicationDbContext = _context.Activities.Include(a => a.ActivityType).Include(a => a.Module);
            //return View(await applicationDbContext.ToListAsync());

            var model = await mapper.ProjectTo<ActivityListViewModel>(_context.Activities).ToListAsync();
            return View(model);

        }

        // GET: Activities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activity = await _context.Activities
                .Include(a => a.ActivityType)
                .Include(a => a.Module)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (activity == null)
            {
                return NotFound();
            }

            return View(activity);
        }

        // GET: Activities/Create
        [Authorize(Roles = "Teacher")]
        public IActionResult Create(int? id)
        {
            //ViewData["ActivityTypeId"] = new SelectList(_context.Set<ActivityType>(), "Id", "Name");
            //ViewData["ModuleId"] = new SelectList(_context.Set<Module>(),"Id", "Name", ModuleId);
            return View();
        }

        // POST: Activities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Create(CreateActivityViewModel activity, int id)
        {
            if (activity.EndDate < activity.StartDate)
            {
                ModelState.AddModelError("EndDate", "Sluttiden kan inte vara tidigare än starttiden");
            }


            if (ModelState.IsValid)
            {
                var model = mapper.Map<Activity>(activity);
                model.ModuleId = id;

                _context.Add(model);
                await _context.SaveChangesAsync();
                TempData["SuccessText"] = $"Aktivitet- {model.Name} - är skapad!";

                if (model.ModuleId == default) return RedirectToAction(nameof(Index));
                var CourseId = _context.Modules.Where(m => m.Id == model.ModuleId).Select(m => m.CourseId).FirstOrDefault();
                return RedirectToAction(nameof(Details), "Courses", new { id = CourseId });
            }
            return View(activity);
        }

        // GET: Activities/Edit/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var activity = await mapper.ProjectTo<ActivityEditViewModel>(_context.Activities).FirstOrDefaultAsync(e => e.Id == id);
            //var activity = await _context.Activities.FindAsync(id);
            if (activity == null)
            {
                return NotFound();
            }
           // ViewData["ActivityTypeId"] = new SelectList(_context.Set<ActivityType>(), "Id", "Name", activity.ActivityTypeId);
            //ViewData["ModuleId"] = new SelectList(_context.Set<Module>(), "Id", "Name", activity.ModuleId);
            return View(activity);
        }

        // POST: Activities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int id,  ActivityEditViewModel activity)
        {
            
            if (id != activity.Id)
            {
                return NotFound();
            }

            if (activity.EndDate < activity.StartDate)
            {
                ModelState.AddModelError("EndDate", "Sluttiden kan inte vara tidigare än starttiden");
            }
           /* var found = await _context.Courses.AnyAsync(p => (p.Name == activity.Name) && (p.Id != activity.Id));
            if (found)
            {
                ModelState.AddModelError("Name", "Det finns redan en kurs med denna namn");
            }*/

            var model = mapper.Map<Activity>(activity);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivityExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["SuccessText"] = $"Aktivitet: {activity.Name} - är uppdaterad!";
                //return RedirectToAction(nameof(Index));
                var CourseId = _context.Modules.Where(m => m.Id == model.ModuleId).Select(m => m.CourseId).FirstOrDefault();
                return RedirectToAction(nameof(Details), "Courses", new { id = CourseId});
            }

            TempData["FailText"] = $"Något gick fel! Aktivitet: {activity.Name} - är inte uppdaterad!";

            return View(activity);
        }

        // GET: Activities/Delete/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activity = await mapper.ProjectTo<DeleteActivityViewModel>(_context.Activities).FirstOrDefaultAsync(t => t.Id == id);
            //var activity = await _context.Activities
                //.Include(a => a.ActivityType)
                //.Include(a => a.Module)
                //.FirstOrDefaultAsync(m => m.Id == id);
            if (activity == null)
            {
                return NotFound();
            }

            return View(activity); ;
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ModuleId = _context.Activities.Where(a => a.Id == id).Select(a => a.ModuleId).FirstOrDefault();
            var CourseId = _context.Modules.Where(m => m.Id == ModuleId).Select(m => m.CourseId).FirstOrDefault();

            var model = await mapper.ProjectTo<DeleteActivityViewModel>(_context.Activities).FirstOrDefaultAsync(t => t.Id == id);
            var activity = await _context.Activities.FindAsync(id);
            _context.Activities.Remove(activity);
            await _context.SaveChangesAsync();
            TempData["SuccessText"] = $"Aktivitet: {activity.Name} - är raderad!";
            return RedirectToAction(nameof(Details), "Courses", new { id = CourseId });
        }

        private bool ActivityExists(int id)
        {
            return _context.Activities.Any(e => e.Id == id);
        }


        private bool ModuleNotEmpty()
        {
            return (!_context.Modules.Any());
        }

    }
}

LMSLexicon20/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMSLexicon20.Data;
using LMSLexicon20.Models;
using AutoMapper;
using LMSLexicon20.Models.ViewModels;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Authorization;
using LMSLexicon20.Extensions;
using LMSLexicon20.Filters;
using LMSLexicon20.ViewModels;

namespace LMSLexicon20.Controllers
{
    public class ModulesController : Controller
    {
        private ApplicationDbContext context;
        private readonly IMapper mapper;
        
        public ModulesController(ApplicationDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        // GET: Modules
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Index()
        {
            var modules = await context.Modules.Include(m => m.Course).ToListAsync();
            var viewModel = await mapper.ProjectTo<IndexModuleViewModel>
                (context.Modules.Include(m => m.Course)).ToListAsync();
            return View(viewModel);
        }

        // GET: Modules/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = await context.Modules
                .Include(m => m.Course)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (model == null)
            {
                return NotFound();
            }
            var viewModel = mapper.Map<DetailModuleViewModel>(model);
            viewModel.Id = id;
            return View(viewModel);
        }
        //Get
        [Authorize(Roles = "Teacher")]
        public IActionResult CreateModule(int id)
        {
            TempData["courseId"] = id;
            if (Request.IsAjax())
                return PartialView("CreateModulePartialView");
            return View();
        }
        //Post
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Name,StartDate,EndDate,Description,CourseId")] Module model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        context.Add(model);
        //        await context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["CourseId"] = new SelectList(context.Courses, "Id", "Id", model.CourseId);
        //    return View(model);
        //}
        ////Post
        //[HttpPost]
        [Authorize(Roles = "Teacher")]
        [ValidateAjax]
        [HttpPost]
        public async Task<IActionResult> CreateModule(CreateModuleViewModel viewModel, int id)
        {
            var nameExists = context.Modules
                .Where(m => m.CourseId == id)
                .Any(m => m.Name == viewModel.Name);
            if (nameExists)
                ModelState.AddModelError("Name", "Namnet används redan i denna kurs");


            if (ModelState.IsValid)
            {
                var model = mapper.Map<Module>(viewModel);
                model.CourseId = id;

                await context.Modules.AddAsync(model);
                await context.SaveChangesAsync();

                if (Request.IsAjax())
                {
                    var ajaxModel = new ModuleDetailVM
                    {
                        Id = model.Id,
                        Name = model.Name,
                        StartDate = model.StartDate,
                        EndDate = model.EndDate,
                        Description = model.Description,
                        CourseId = model.CourseId,
                        Expanded = false
                    };
                    
                    return PartialView("CreateModuleSuccessPartialView", ajaxModel);
                }

                TempData["SuccessText"] = $"Modulen: {model.Name} - är skapad!";
                return RedirectToAction(nameof(Details), "Courses", new { id = model.CourseId });
            }
            if (Request.IsAjax())
            {
                return PartialView("CreateModulePartialView", viewModel);
            }

            return View(viewModel);
        }

        // GET: Modules/Edit/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await context.Modules.FindAsync(id);
            if (model==null)
            {
                NotFound();
            }
            var viewModel = mapper.Map<EditModuleViewModel>(model);
            //För att kunna gå tillbaka till kurs
            TempData["CourseId"] = model.CourseId;
            return View(viewModel);
        }

        // POST: Modules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Edit(EditModuleViewModel viewModel, int id)
        {

            var found = await context.Modules
                .Where(m => m.CourseId == viewModel.CourseId)
                .AnyAsync(p => (p.Name == viewModel.Name)
                && (p.Id != id));
            if (found)
            {
                ModelState.AddModelError("Name", "Namnet används redan i denna kurs");
            }

            if (ModelState.IsValid)
            {
                var model = await context.Modules.FindAsync(id);

                model.Name = viewModel.Name;
                model.StartDate = viewModel.StartDate;
                model.EndDate = viewModel.EndDate;
                model.Description = viewModel.Description;
                
                //context.Entry(model).Property(p => p.CourseId).IsModified = false;

                try
                {
                    context.Update(model);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuleExists(model.Id))
                        return NotFound();
                    else
                        throw;
                }
                TempData["SuccessText"] = $"Modulen {model.Name} har uppdaterats";
                return RedirectToAction(nameof(Details), "Courses", new { id = model.CourseId });
            }
            return View(viewModel);
        }

        // GET: Modules/Delete/5
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await context.Modules
                .Include(m => m.Course)
                .Include(m => m.Activities)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (model == null)
            {
                return NotFound();
            }
            var viewModel = mapper.Map<DeleteModuleViewModel>(model);
            return View(viewModel);
        }

        // POST: Modules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var module = await context.Modules.FindAsync(id);
            //var activities = module.Activities;
            var activities = await context.Activities.Where(a => a.ModuleId == module.Id).ToListAsync();
            var courseId = module.CourseId;
            var name = module.Name;

            if (activities != null)
                foreach (var activity in activities) context.Activities.Remove(activity);
            context.Modules.Remove(module);
            await context.SaveChangesAsync();

            TempData["SuccessText"] = $"Modulen {name} har tagits bort";
            return RedirectToAction(nameof(Details), "Courses", new { id = courseId });
        }

        private bool ModuleExists(int id)
        {
            return context.Modules.Any(e => e.Id == id);
        }
    }
}

LMSLexicon20/Views/Modules/CreateModule.cshtml
@model LMSLexicon20.Models.ViewModels.CreateModuleViewModel

@{
    ViewData["Title"] = "Skapa Modul";
}
    <h2 class="bg-dark shadow-lg border rounded-lg font-weight-bold text-light p-4">SKAPA NY MODUL</h2><hr />
<div class="row">
    <div class="col-md-6 p-3">
        <form asp-action="CreateModule">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Tidsperiod</label>
                <div class="form-inline">
                    <input asp-for="StartDate" class="form-control" />
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span><br />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                    @*<label asp-for="EndDate" class="control-label"></label>*@
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" maxlength="500"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-sm btn-primary">
                    <i class="fas fa-plus-circle"></i>
                    <span>Lägg till </span>
                    <i class="fas fa-layer-group"></i>
                </button>

            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Courses" asp-action="Details" asp-route-id='@TempData["courseId"]'>Tillbaka till kurs</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LMSLexicon20/Views/Modules/CreateModulePartialView.cshtml
@model CreateModuleViewModel

@{
    ViewData["Title"] = "Skapa Modul";
}
@*<h2 class="bg-dark shadow-lg border rounded-lg font-weight-bold text-light p-4">SKAPA NY MODUL</h2>
<hr />*@
<div class="row">
    <div class="col-md-6 p-3">
        <form asp-action="CreateModule"
              data-ajax="true"
              data-ajax-method="POST"
              data-ajax-mode="after"
              data-ajax-update="#accordion"
              data-ajax-success="DisplayCreateModuleSuccess">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Tidsperiod</label>
                <div class="form-inline">
                    <input asp-for="StartDate" class="form-control" />
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span><br />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                    @*<label asp-for="EndDate" class="control-label"></label>*@
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" maxlength="500"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group btn-group-sm">
                <button type="submit" class="btn btn-sm btn-outline-primary a-btn-slide-text">
                    <i class="fas fa-plus-circle" aria-hidden="true"></i>&nbsp;Lägg till&nbsp;
                    <i class="fas fa-layer-group" aria-hidden="true"></i>
                </button>
                <a href="javascript:history.go(0)" class="btn btn-sm btn-outline-secondary a-btn-slide-text">
                    <i class="fas fa-ban" aria-hidden="true"></i>
                    <span>Avbryt</span>
                </a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LMSLexicon20/Views/Modules/CreateModuleSuccessPartialView.cshtml
@model ModuleDetailVM

@{
    var clsDD = User.IsInRole("Teacher") ? "ddzone" : "";
}

<div class="card">
    <div class="card-header card-header-module" id="@String.Format($"heading{Model.Id}")">
        <div class="mb-0">

            <div class="container">
                <div class="row">

                    <div class="col-5 @clsDD" data-domain="module" data-id="@Model.Id">
                        <button class="btn btn-link" data-toggle="collapse" data-target="@String.Format($"#collapse{Model.Id}")" aria-expanded="@Model.Expanded" aria-controls="@String.Format($"collapse{Model.Id}")">
                            <i class="fas fa-layer-group"></i>
                            <span class="course-module-name">@Html.DisplayFor(modelItem => Model.Name)</span>
                        </button>
                    </div>

                    <div style="padding-top:10px" class="col-3">
                        <h6 style="font-weight:400">
                            @{var cls = ""; var tt = "";}
                            @if (User.IsInRole("Teacher"))
                            {
                                cls = Model.StartDateOverlap ? "warning_start_overlap" : "";
                                tt = Model.StartDateOverlap ? "Modulen startdatum överlappar en annan modul" : "";
                                cls = Model.StartDateToEarly ? "warning_to_early" : Model.StartDateToLate ? "warning_to_late" : cls;
                                tt = Model.StartDateToEarly ? "Modulens startdatum ligger innan kursens startdatum" : Model.StartDateToLate ? "Modulens startdatum ligger efter kursens slutdatumdatum" : tt;
                            }
                            <span class="@cls" data-toggle="tooltip" title="@tt">@Html.DisplayFor(modelItem => Model.StartDate)</span>
                            <span>&nbsp;-&nbsp;</span>
                            @if (User.IsInRole("Teacher"))
                            {
                                cls = Model.EndDateOverlap ? "warning_end_overlap" : "";
                                tt = Model.EndDateOverlap ? "Modulen slutdatum överlappar en annan modul" : "";
                                cls = Model.EndDateToEarly ? "warning_to_early" : Model.EndDateToLate ? "warning_to_late" : cls;
                                tt = Model.EndDateToEarly ? "Modulens slutdatum ligger innan kursens startdatum" : Model.EndDateToLate ? "Modulens slutdatum ligger efter kursens slutdatumdatum" : tt;
                            }
                            <span class="@cls" data-toggle="tooltip" title="@tt">@Html.DisplayFor(modelItem => Model.EndDate)</span>
                        </h6>
                    </div>

                    <div class="col-3">
                        @if (User.IsInRole("Teacher"))
                        {

                            <div style="font-size:small;font-weight:400">
                                <div style="float: right" class="btn-group btn-group-xs" role="group">
                                    <a href="@Url.Action("Delete", "Modules", new { id = Model.Id })" class="btn btn-sm btn-outline-danger a-btn-slide-text">
                                        <span class="fas fa-times" aria-hidden="true"></span>
                                        <span>Ta bort</span>
                                    </a>
                                    <a href="@Url.Action("Edit", "Modules", new { id = Model.Id })" class="btn btn-sm btn-outline-secondary a-btn-slide-text">
                                        <i class="fas fa-edit" aria-hidden="true"></i>
                                        <span>Ändra</span>
                                    </a>
                                </div>
                            </div>
                        }
                    </div>

                    @{ cls = Model.Expanded ? "fa-caret-down" : "fa-caret-left"; }
                    <div class="col-1">
                        <button style="padding:0" class="btn btn-link" data-toggle="collapse" data-target="@String.Format($"#collapse{Model.Id}")" aria-expanded="@Model.Expanded" aria-controls="@String.Format($"collapse{Model.Id}")">
                            <span class="fa-stack fa-sm">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fas @cls fa-stack-1x fa-inverse"></i>
                            </span>
                        </button>
                    </div>
                </div> @*row*@
            </div> @*container*@
        </div>
    </div> @*card-header*@

    @{ cls = Model.Expanded ? " show" : ""; }
    <div id="@String.Format($"collapse{Model.Id}")" class="collapse @cls" aria-labelledby="@String.Format($"heading{Model.Id}")" data-parent="#accordion">
        <div class="card-body">

            <span>@Html.DisplayFor(modelItem => Model.Description)</span>

            <div class="row" style="display: flex; justify-content: flex-end; padding-right:20px">
                @if (User.IsInRole("Teacher"))
                {
                    <div class="fileinput" style="display: flex; justify-content: flex-end; padding-top: 10px;">
                        <button type="button" class="btn btn-sm btn-outline-warning">
                            <span class="fas fa-plus-circle" aria-hidden="true"></span>&nbsp;
                            <span>Lägg till dokument&nbsp;<i class="fas fa-file"></i></span>
                        </button>
                    </div>
                }
                &nbsp;
                @if (User.IsInRole("Teacher"))
                {
                    <div style="display: flex; justify-content: flex-end; padding-top: 10px;">
                        <a href="@Url.Action("Create", "Activities", new { id = Model.Id })" class="btn btn-sm btn-outline-primary a-btn-slide-text">
                            <span class="fas fa-plus-circle" aria-hidden="true"></span>&nbsp;
                            <span>Lägg till aktivitet&nbsp;<i class="fas fa-tasks"></i></span>
                        </a>
                    </div>
                }
            </div>
            <br />
        </div>
    </div>
</div>

LMSLexicon20/Views/Modules/Delete.cshtml
@model LMSLexicon20.Models.ViewModels.DeleteModuleViewModel

@{
    ViewData["Title"] = "Ta bort modul";
}

<h2 class="bg-dark shadow-lg border rounded-lg font-weight-bold text-light p-4">TA BORT MODUL</h2>
<h4>Är du säker på att du vill ta bort denna modul?</h4>
<p>Alla aktiviteter @*(och dokument?)*@ som tillhör modulen kommer att raderas</p>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Course.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Activities)
            <span> (@Model.Activities.Count())</span>
        </dt>
        @if (Model.Activities.Count() <= 0)
        {
            <dd class="col-sm-10">Inga aktiviteter</dd>
        }
        else
        {
            <dd class="col-sm-10">
                @foreach (var act in Model.Activities)
                {
                    @Html.DisplayFor(modelItem => act.Name)<br />
                }
            </dd>
        }

    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div class="btn-group btn-group-xs">
            <button type="submit" class="btn btn-sm btn-danger">
                <i class="fas fa-times"></i>
                <span>Ta bort</span>
            </button>
            <a asp-controller="Courses" asp-action="Details" asp-route-id="@Model.Course.Id" class="btn btn-sm btn-secondary">
                <i class="fas fa-ban"></i>
                <span>Avbryt</span>
            </a>
        </div>
    </form>
</div>